name: Deploy to GitHub Pages


on:
  push:
    branches: [main]


jobs:
  rssandsitemap:
    name: Building sitemap, and RSS
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run : npm install grey-matter
      - name: Build sitemap and RSS
        run : node ./scripts/buildxml.js
      - name: update file and push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "SiteMap and RSS updated"
          git push

  check:
    name: Check if everything is ok
    runs-on: ubuntu-latest
    needs: [rssandsitemap]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Go to public folder
        run : cd public
      - name: Pull latest changes
        run : git pull
      - name: Check if everything is ok
        run : (ls sitemap.xml && ls rss.xml && echo "Everything is ok") || (echo "Something is wrong" && exit 1)

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check]

    strategy:
      matrix:
        node-version: [16.x]


    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
      - name: Installing dependencies
        run: npm i @next/swc-linux-x64-gnu @next/swc-linux-x64-musl
      - name: Build project
        run: npm run build
      - name: Export static files
        run: npm run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
