name: Deploy Feed and Sitemap


on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  rssandsitemap:
    name: Building sitemap, and RSS
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run : npm install moment frontmatter
      - name: Build sitemap and RSS
        run : node ./scripts/buildxml.js
      - name: Remove unnecessary modules
        run : npm remove moment
      - name: update file and push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "SiteMap and RSS updated"
          git push
